name: reviewdog
description: run reviewdog

inputs:
  args:
    required: true
    description: reviewdog command line argumetnts
  
runs:
  using: composite
  steps:
    - name: Install reviewdog
      shell: bash
      run: |
        sudo curl -fL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s
        
    - name: Run reviewdog
      shell: bash
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_TOKEN }}
      run: |
        reviewdog ${{ inputs.args }}
